{
  pkgs ? import <nixpkgs> { },
  system,
  inputs,
}:
let
  pythonPackages =
    ps: with ps; [
      #--- backend ---
      #all required dependencies + this projects package itself (required for sphinx)
      click
      argon2-cffi
      fastapi
      pydantic
      email-validator
      psycopg
      psycopg-pool
      redis
      authlib
      bonsai
      itsdangerous
      pycryptodome
      aiosmtplib
      granian
      setproctitle
      uvicorn
      python-multipart
      httpx
      platformdirs
      pyaml-env

      #optional dependencies: development_mode
      watchfiles

      #optional dependencies: docs
      sphinx
      sphinxcontrib-openapi
      autodoc-pydantic
      sphinx-mdinclude
      sphinx-rtd-theme

      #for the tests: tests
      pytest
      pytest-timeout
      smtpdfix

      #--- runner ---
      #all required dependencies + this projects package itself (required for sphinx)
      #(dontCheckPythonPkg project-W-runner)
      httpx
      click
      pydantic
      platformdirs
      pyaml-env

      #optional dependencies: not_dummy (nixpkgs only has an old version of WhisperX)
      #hf-xet
      #whisperx
    ];
  pre-commit-check = inputs.pre-commit-hooks.lib.${system}.run {
    src = ./.;
    hooks = {
      end-of-file-fixer.enable = true;
      trim-trailing-whitespace.enable = true;
      check-added-large-files.enable = true;
      check-merge-conflicts.enable = true;
      check-symlinks.enable = true;
      check-docstring-first.enable = true;
      check-builtin-literals.enable = true;
      check-python.enable = true;
      python-debug-statements.enable = true;
      biome = {
        enable = true;
        files = "frontend*";
        types_or = [ ];
      };
      ruff = {
        enable = true;
        files = "backend*|runner*";
        excludes = [ "doc/conf.py" ];
      };
      ruff-format = {
        enable = true;
        files = "backend*|runner*";
      };
      nixfmt-rfc-style.enable = true;
    };
  };
in
pkgs.mkShell {
  buildInputs =
    with pkgs;
    [
      (python312.withPackages pythonPackages)
      nodejs_24
      corepack_24
    ]
    ++ pre-commit-check.enabledPackages;

  shellHook = ''
    localOverwriteFile=".pre-commit-config.yaml"
    if ! grep -q "This file was generated by git-hooks.nix" "$localOverwriteFile"; then
        git update-index --skip-worktree "$localOverwriteFile"
        rm "$localOverwriteFile"
    fi
    git update-index --skip-worktree "backend/config.yml"
    git update-index --skip-worktree "runner/config.yml"
  ''
  + pre-commit-check.shellHook;
}
