# This is a dummy config intended for development purposes only!
disableOptionValidation: true
clientURL: http://localhost:5173/#
databasePath: .
loginSecurity:
  sessionSecretKey: abcdefghijklmnopqrstuvwxyz0123456789
