services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

  redis:
    image: redis:${REDIS_VERSION}
    ports:
      - "6379:6379"

  project-w:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
        FRONTEND_BRANCH_NAME: ${FRONTEND_BRANCH_NAME}
    network_mode: "host" #for smtpdfix
    ports:
      - "8443:8443"
    volumes:
      - ./backend-config:/etc/xdg/project-W/
    depends_on:
      - postgres
      - redis
    profiles: [ app ]
