name: Delete untagged containers

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  delete-untagged-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged containers
        uses: actions/delete-package-versions@v5
        with:
          delete-only-untagged-versions: true
          min-versions-to-keep: 0
          package-name: 'project-w'
          package-type: 'container'
