name: Delete untagged containers

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  delete-untagged-containers:
    steps:
      - name: Delete untagged containers
        uses: actions/delete-package-versions@v5
        with:
          delete-only-untagged-versions: true
          min_versions_to_keep: 0
          package_name: 'your-docker-container-package-name'
          package_type: 'container'
